// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OficinaMecanica.Infrastructure.Context;

#nullable disable

namespace OficinaMecanica.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OficinaMecanica.Models.Budget", b =>
                {
                    b.Property<int>("IdBudget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClintId")
                        .HasColumnType("int");

                    b.Property<int>("vehicle")
                        .HasColumnType("int");

                    b.HasKey("IdBudget");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("OficinaMecanica.Models.BudgetItens", b =>
                {
                    b.Property<int>("idBudGetItens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BudGetId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idBudGetItens");

                    b.HasIndex("BudGetId");

                    b.ToTable("BudGetItens");
                });

            modelBuilder.Entity("OficinaMecanica.Models.BudgetItens", b =>
                {
                    b.HasOne("OficinaMecanica.Models.Budget", "Budget")
                        .WithMany("BudgetItensList")
                        .HasForeignKey("BudGetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("OficinaMecanica.Models.Budget", b =>
                {
                    b.Navigation("BudgetItensList");
                });
#pragma warning restore 612, 618
        }
    }
}
